/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import datos.Empleado;
import datos.Empresa;

/**
 *
 * @author DAM17
 */
public class Administrador extends javax.swing.JFrame {

    private Empresa email;
    private int usuarioValidado;
    private PanelAltaUsuario palta;
    private PanelModificaciones pmodifi;

    /**
     * Creates new form Administrador
     */
    public Administrador(Empresa email, int usuarioValidado) {
        this.email = email;
        this.usuarioValidado = usuarioValidado;
        initComponents();
        setSize(600, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNuevoUsuario = new javax.swing.JMenuItem();
        mnuModificarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuDesconectar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Usuarios");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuNuevoUsuario.setText("Nuevo usuario");
        mnuNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevoUsuario);

        mnuModificarUsuario.setText("Modificar");
        mnuModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuModificarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuDesconectar.setText("Desconectar");
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDesconectar);

        mnuSalir.setText("Salir de la aplicación");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
        pack();
        System.exit(0); // si no no acaba la aplicacion
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        new Validacion(email).setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnuNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoUsuarioActionPerformed
        quitarPaneles(); // para no poder poner el mismo panel varias veces 
        palta = new PanelAltaUsuario(email);
        this.add(palta);
        // no se ve porque no sabe donde ponerlo
        pack();

    }//GEN-LAST:event_mnuNuevoUsuarioActionPerformed

    private void mnuModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarUsuarioActionPerformed

    //Aqui relacionamos el panel de modificar los datos a la ventana del administrador:
        quitarPaneles();
        pmodifi = new PanelModificaciones();
        this.add(pmodifi);
        pack();
    }//GEN-LAST:event_mnuModificarUsuarioActionPerformed

    private void quitarPaneles() {
        try {
            this.email = palta.email;
            remove(palta);
        } catch (Exception e) {

        }
        try {
            remove(pmodifi);
        } catch (Exception e) {

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuModificarUsuario;
    private javax.swing.JMenuItem mnuNuevoUsuario;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
